version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_data
    ports:
      - "5432:5432"
    volumes:
      - ./src/data_etl/storage/timescaledb_schema.sql:/docker-entrypoint-initdb.d/timescaledb_schema.sql
    restart: unless-stopped