name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ] || [ -f setup.py ]; then
            pip install -e .
          else
            echo "Error: no requirements.txt, setup.py or pyproject.toml found at repo root."
            exit 1
          fi
          pip install ruff==0.4.4 black==24.4.2 pytest==8.2.0 pytest-cov

      - name: Lint (obligatorio)
        run: |
          ruff check .
          black --check .

      - name: Run tests with coverage
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd):$(pwd)/financial-data-pipeline:$(pwd)/src"
          pytest --cov=. --cov-report=xml --cov-report=term -q
